buildscript {

    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.google.gms:google-services:4.3.10'
        classpath 'com.google.android.gms:strict-version-matcher-plugin:1.2.0'
        classpath 'com.android.tools.build:gradle:4.2.2'
        classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.7.10'
    }

}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'

android {
    
    namespace 'minefarts.smarttube'

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    compileSdkVersion 33

    buildToolsVersion '30.0.3'

    defaultConfig {

        applicationId "minefarts.smarttube"

        minSdkVersion 21
        targetSdkVersion 26

        def now = new Date()
        versionName now.format('yy.MM.dd')
        versionCode now.format('yyMMdd').toInteger()
    
    }
 
    buildTypes {
        debug {
            minifyEnabled false
            shrinkResources false
        }
    }

}

apply plugin: 'com.google.gms.google-services'

repositories {
    google()
    mavenCentral()
    maven { url 'https://jitpack.io' }
}

apply from: new File (rootDir, "lib/yuliskov/MediaServiceCore/SharedModules/constants.gradle")

dependencies {

    implementation 'androidx.leanback:leanback:' + leanbackXVersion
    implementation 'androidx.leanback:leanback-preference:' + leanbackXVersion
    implementation 'androidx.recommendation:recommendation:' + leanbackXVersion
    implementation 'androidx.annotation:annotation:' + annotationXVersion
    implementation 'androidx.recyclerview:recyclerview:' + recyclerviewXVersion
    implementation 'androidx.media:media:' + mediaXVersion
    implementation 'androidx.multidex:multidex:' + multiDexVersion

    implementation 'com.github.bumptech.glide:glide:' + glideVersion
    implementation 'com.github.bumptech.glide:annotations:' + glideVersion
    annotationProcessor 'com.github.bumptech.glide:compiler:' + glideVersion
    
    implementation 'com.github.zjupure:webpdecoder:' + webpDecoderVersion

    implementation project(':exoplayer-library-core')
    implementation project(':exoplayer-library-ui')
    
    implementation project(':exoplayer-extension-leanback')
    implementation project(':exoplayer-extension-mediasession')

    implementation project(':fragment-1.1.0')
    implementation project(':leanback-1.0.0')
    implementation project(':common')
    implementation project(':sharedutils')
    implementation project(':mediaserviceinterfaces')
    implementation project(':youtubeapi')
    implementation project(':chatkit')

    implementation 'io.reactivex.rxjava2:rxandroid:' + rxAndroidVersion
    implementation 'io.reactivex.rxjava2:rxjava:' + rxJavaVersion

    implementation 'net.gotev:speech:' + gotevSpeechVersion

    implementation 'com.google.android.flexbox:flexbox:3.0.0'
    
}
