
buildscript {

    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.2.2'
        classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.7.10'
        classpath 'com.google.gms:google-services:4.3.15'
        classpath 'com.google.android.gms:strict-version-matcher-plugin:1.2.4'
    }

}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'

android {

    namespace 'minefarts.smarttube'
    
    compileSdkVersion 33
    
    buildToolsVersion '30.0.3'

    defaultConfig {

        applicationId "minefarts.smarttube"
        
        minSdkVersion 21
        targetSdkVersion 33

        def now = new Date()
        versionName now.format('yy.MM.dd')
        versionCode now.format('yyMMdd').toInteger()
        
        multiDexEnabled true 
    
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    buildTypes {
        debug {
            minifyEnabled false
            shrinkResources false
        }
    }
    
}

apply plugin: 'com.google.gms.google-services'

repositories {
    google()
    mavenCentral()
    maven { url 'https://jitpack.io' }
}

dependencies {

    // Pre-compiled yuliskov binaries
    implementation fileTree(dir: 'src/main/aar', include: ['*.aar'])

    // Static analysis quality
    compileOnly 'org.checkerframework:checker-qual:2.5.0'
    compileOnly 'org.checkerframework:checker-compat-qual:2.5.0'

    // Static Logger
    implementation 'org.slf4j:slf4j-nop:1.7.36'

    // Jetpack core & architecture
    implementation 'androidx.core:core:1.9.0'
    implementation 'androidx.core:core-ktx:1.9.0'
    implementation 'androidx.activity:activity:1.6.0'
    implementation 'androidx.appcompat:appcompat:1.5.0'
    implementation 'androidx.multidex:multidex:2.0.1'
    implementation 'androidx.annotation:annotation:1.5.0'
    implementation 'androidx.loader:loader:1.0.0'
    implementation 'androidx.interpolator:interpolator:1.0.0'

    // Android TV & Leanback
    implementation 'androidx.tvprovider:tvprovider:1.0.0'
    implementation 'androidx.recommendation:recommendation:1.0.0'
    implementation 'androidx.leanback:leanback-preference:1.0.0'

    // Media & playback
    implementation 'androidx.media:media:1.2.0' 

    // UI components & layouts
    implementation 'androidx.recyclerview:recyclerview:1.2.1'
    implementation 'androidx.viewpager:viewpager:1.0.0'
    implementation 'com.google.android.material:material:1.5.0'
    implementation 'com.google.android.flexbox:flexbox:3.0.0'
    implementation 'androidx.preference:preference:1.2.0'

    // System utilities & background processing
    implementation 'androidx.work:work-runtime:2.7.1'
    implementation 'androidx.browser:browser:1.4.0'
    implementation 'androidx.webkit:webkit:1.7.0'
    implementation 'net.gotev:speech:1.1.7'

    // Core window extensions required by modern chromium system webviews
    implementation 'androidx.window:window:1.1.0'
    implementation 'androidx.window:window-core:1.1.0'

    // Image loading
    implementation 'com.github.bumptech.glide:glide:4.11.0'
    implementation 'com.github.bumptech.glide:annotations:4.11.0'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.11.0'

    // Networking (OkHttp 3.12.x pipeline & Retrofit)
    implementation 'com.squareup.okhttp3:okhttp:3.12.13'
    implementation 'com.squareup.okhttp3:okhttp-dnsoverhttps:3.12.13'
    implementation 'com.squareup.okhttp3:logging-interceptor:3.12.13'
    implementation 'com.squareup.retrofit2:retrofit:2.5.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.5.0'
    implementation 'com.localebro:okhttpprofiler:1.0.8'
    implementation 'dnsjava:dnsjava:2.1.9'
    implementation 'info.guardianproject.netcipher:netcipher:2.1.0'

    // JSON processing
    implementation 'com.google.code.gson:gson:2.8.2'
    implementation 'com.jayway.jsonpath:json-path:2.4.0'
    implementation 'com.grack:nanojson:1.7'

    // Asynchronous programming
    implementation 'io.reactivex.rxjava2:rxandroid:2.1.1'
    implementation 'io.reactivex.rxjava2:rxjava:2.2.21'

    // Kotlin runtime & coroutines
    implementation 'org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.7.10'
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.5.2'

    // Embedded JavaScript engine
    implementation 'com.caoccao.javet:javet-android:1.0.7'

    // Caching utilities
    implementation 'com.jakewharton:disklrucache:2.0.2'

}

configurations.configureEach {

    exclude group: 'androidx.fragment', module: 'fragment'
    exclude group: 'androidx.fragment', module: 'fragment-ktx'
    exclude group: 'androidx.leanback', module: 'leanback'

    exclude group: 'org.jetbrains.kotlin', module: 'kotlin-stdlib-jdk7'
    exclude group: 'org.jetbrains.kotlin', module: 'kotlin-stdlib-jdk8'
    
}
