
include ':smarttubetv'
include ':exoplayer-library', ':exoplayer-extension-leanback', ':exoplayer-extension-mediasession'
include ':fragment-1.1.0', ':leanback-1.0.0', ':common', ':sharedutils', ':mediaserviceinterfaces', ':youtubeapi', ':chatkit'
include ':commons-io-2.8.0', ':j2v8'

gradle.ext.sharedModulesConstants = new File(rootDir, 'pkg/constants.gradle')

settings.rootProject.children.each { proj ->

    proj.projectDir = new File(rootDir, "pkg/${proj.name}")

    if (!proj.projectDir.exists()) {

        proj.projectDir = new File(rootDir, "build/stubs/${proj.name}")
        
        gradle.rootProject {
            project(":${proj.name}") {
                configurations.maybeCreate("default")                
                artifacts {
                    add('default', new File(rootDir, "pkg/${proj.name}.aar"))
                }
            }
        }
        
    }
        
}

