
// Iter through children of lib/aar
(new File(rootDir, '/lib/aar/')).eachFile { aarFile ->

    // Parse project name from file name
    String name = aarFile.name.replaceAll(/\.aar$/, '')

    // Register project
    include ":${name}"
    project(":${name}").projectDir = new File(rootDir, "/build/stubs/${name}/")
    
    // Wire the AAR binary as the project output artifact
    gradle.rootProject {
        project(":${name}") {
            configurations.create('default')
            artifacts {
                add('default', aarFile)
            }
        }
    }

}

