package minefarts.smarttube.exoplayer.other;

import android.app.Activity;
import android.content.Context;
import android.graphics.Color;
import android.graphics.Typeface;
import android.os.Build.VERSION;
import android.util.TypedValue;
import android.view.View;
import android.view.accessibility.CaptioningManager;
import android.view.accessibility.CaptioningManager.CaptionStyle;

import androidx.annotation.RequiresApi;
import androidx.core.content.ContextCompat;

import minefarts.exoplayer2.text.CaptionStyleCompat;
import minefarts.exoplayer2.text.Cue;
import minefarts.exoplayer2.text.TextOutput;
import minefarts.exoplayer2.ui.SubtitleView;

import minefarts.sharedutils.helpers.Helpers;
import minefarts.smarttube.R;
import minefarts.smarttube.prefs.AppPrefs;
import minefarts.smarttube.prefs.common.DataChangeBase.OnDataChange;
import minefarts.smarttube.prefs.PlayerData;

import java.util.ArrayList;
import java.util.List;

public class SubtitleManager implements TextOutput, OnDataChange {

    private final SubtitleView mSubtitleView;
    private final Context mContext;

    private final AppPrefs mPrefs;
    private final PlayerData mPlayerData;
    private CharSequence subsBuffer;

    public SubtitleManager(Activity activity, int subViewId) {
        
        mContext = activity;
        
        mSubtitleView = activity.findViewById(subViewId);

        mPrefs = AppPrefs.instance(activity);
        
        mPlayerData = PlayerData.instance(activity);
        mPlayerData.setOnChange(this);
        
        onDataChange();

    }

    @Override
    public void onDataChange() {
        if (mSubtitleView != null) {

            // disable default style
            mSubtitleView.setApplyEmbeddedStyles(false);
            
            mSubtitleView.setStyle(new CaptionStyleCompat(
                ContextCompat.getColor(mContext, R.color.light_grey),
                ContextCompat.getColor(mContext, R.color.transparent), 
                Color.TRANSPARENT,
                CaptionStyleCompat.EDGE_TYPE_DROP_SHADOW,
                ContextCompat.getColor(mContext, R.color.black), 
                Typeface.DEFAULT_BOLD
            ));

            mSubtitleView.setFixedTextSize(
                TypedValue.COMPLEX_UNIT_PX, 
                0.8f * mSubtitleView.getContext().getResources().getDimension(R.dimen.subtitle_text_size)
            );

            mSubtitleView.setBottomPaddingFraction(.05f);
        }
    }

    @Override
    public void onCues(List<Cue> cues) {
        if (mSubtitleView != null) {

            List<Cue> result = new ArrayList<>();

            for (Cue cue : cues) {
                // Autogenerated subs repeated lines fix
                final String textStr = cue.text.toString();
                if (Helpers.endsWithAny(textStr, "\n", " ")) { // vtt subs format
                    subsBuffer = textStr;
                } else if (textStr.contains("\n")) { // ttml subs format
                    //CharSequence text = subsBuffer != null ? textStr.replace(subsBuffer, "").replace("\n", "") : textStr;

                    CharSequence text;

                    if (subsBuffer != null && textStr.contains(subsBuffer)) {
                        text = textStr.replace(subsBuffer, "").replace("\n", "");
                    } else {
                        text = textStr;
                    }

                    result.add(new Cue(text)); // sub centered by default

                    String[] split = textStr.split("\n");
                    subsBuffer = split.length == 2 ? split[1] : textStr;
                } else {
                    CharSequence text = subsBuffer != null ? textStr.replace(subsBuffer, "") : textStr;
                    result.add(new Cue(text)); // sub centered by default
                    subsBuffer = text;
                }
            }

            mSubtitleView.setCues(result);

        }
    }

    public void show(boolean show) {
        if (mSubtitleView != null) {
            mSubtitleView.setVisibility(show ? View.VISIBLE : View.GONE);
        }
    }

}
